#!/bin/bash

# Publish to Git the changes and generate a new
# tag version.
#
# Maintainer: asccigcc
#
# Usage:
#   ./publish

# read current version
version=$(head -n 1 VERSION)

echo "Preparing to publish"

major=$(echo "$version" | awk -F. '{print $1}')
minor=$(echo "$version" | awk -F. '{print $2}')
patch=$(echo "$version" | awk -F. '{print $3}')

read -p "It is a major, minor or patch version? [M/m/p] " version
if [[ "$version" == "M" ]]; then
  major=$((major+1))
elif [[ "$version" == "m" ]]; then
  minor=$((minor+1))
else
  patch=$((patch+1))
fi

new_version="$major.$minor.$patch"
echo "${new_version}" > VERSION

commit_message="Version ${new_version}"
current_branch=$(git branch --show-current)

git add .
git commit -m "Version ${new_version}"
git push origin ${current_branch}

echo "Published version ${new_version}"
