#!/bin/bash

# SECRETS
#
# Define here your secrets that you want to
# remove from your files when sync from your local.
#
# Example:
#
# secrets["ENV_VARIABLE"]="file_name"

declare -A my_secret

my_secret["BUNDLE_ENTERPRISE__CONTRIBSYS__COM"]=".zshrc_env"
my_secret["BUNDLE_GITHUB__COM"]=".zshrc_env"
my_secret["GITHUB_ACCESS_TOKEN"]=".zshrc_env"

