#!/bin/bash

# Sync dot-files to the git repo
# Maintainer: asccigcc
#
# Usage:
#   ./sync.sh

# Prompt the user to confirm sync
echo -e "\xE2\x9A\x99 Sync Dot-files \xE2\x9A\x99"
echo "The following process will overwrite your git repo."
read -p "Do you want to proceed with the dot-files sync? [y/N] " confirm
if [[ ! $confirm =~ ^[Yy]$ ]]; then
    echo "Syncronization cancelled"
    exit 1
fi

# Load config variables
source config.txt

# Copy dot files
for file in "${files[@]}"; do
    # Check if the destination file already exists
    echo -e "\U0001F504 Preparing sync the file: ${file}"
    cp "${HOME}/${file}" "$file"
    echo "File ${HOME}/${file} copied to git repo"
done

# Copy dot directories
for dir in "${directories[@]}"; do
    echo -e "\U0001F504 Preparing directory ${HOME}/${dir} to sync"
    source_dir="$HOME/$dir/*"
    cp -rf ${source_dir} ${dir}
    echo "Directory ${source_dir} synced"
done

# Clean secrets
source secrets

for key in "${!my_secret[@]}"; do
    echo -e "\U0001F9F9 Cleaning Secret: $key, File: ${my_secret[$key]}"
    sed -i "s/$key=.*/$key=/" ${my_secret[$key]}
done

echo -e "Syncronization complete \xE2\x9A\xA1"

